Dear Data Engineer,

I regret to inform you that some sort of problem has occurred in a dagster job,
if you would be so kind as to give this some attention it would be greatly
appreciated!

Job Failure Message:
{{ context.failure_event.message }}

Step Failures:
{% for step_failure_event in context.step_failure_events %}
    {% if step_failure_event.event_specific_data.error is defined and step_failure_event.event_specific_data.error | length %}
    {% set specific_error = step_failure_event.event_specific_data.error %}
    Error Message: {{ specific_error.message }}
    Stack:
        {% for stack_element in specific_error.stack %}
        {{ stack_element }}
        {%- endfor %}
    Error Source: {{ step_failure_event.event_specific_data.error_source }}
    {% else %}
    Error Message: {{ step_failure_event.message }}
    {% endif %}
{% endfor %}

For details please see, {{ dagit_base_url }}/runs/{{ context.dagster_run.run_id }}

Sincerely,
    Your friendly Dagster Bot
